[platformio]
src_dir = .

[env:gnss_driver]
platform = espressif32@6.12.0
platform_packages =
  platformio/framework-arduinoespressif32@3.20017.241212+sha.dcc1105b
  espressif/toolchain-xtensa-esp32@8.4.0+2021r2-patch5
  platformio/tool-esptoolpy@2.40900.250804
  platformio/tool-scons@4.40801.0
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.flash_mode = dio
board_build.f_flash = 40000000L
build_src_filter = +<main.cpp> +<nvs_guard.cpp> +<production.cpp>
build_flags =
  -I../../../include
  -DBOARD_HAS_PSRAM
  -mfix-esp32-psram-cache-issue
  -DCORE_DEBUG_LEVEL=0
  -Wl,--wrap=nvs_flash_init
  -Wl,--wrap=nvs_flash_erase
  -Wl,--wrap=nvs_open
  -Wl,--wrap=nvs_open_from_partition
  -Wl,--wrap=esp_partition_erase_range
  -Wl,-u,__wrap_nvs_flash_init
  -Wl,-u,__wrap_nvs_flash_erase
  -Wl,-u,__wrap_nvs_open
  -Wl,-u,__wrap_nvs_open_from_partition
  -Wl,-u,__wrap_esp_partition_erase_range
upload_speed = 115200
